In [ ]:
import pandas as pd
import numpy as np
import gdown
import shutil
import re
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# Import file dataset
url = "https://drive.google.com/file/d/1y9qBtV71aY6OtEnhfQAxMTWXBBmdv63i/view?usp=drive_link"
output = "dataset_final.csv"
gdown.download(url, output, quiet=False, fuzzy=True)

dataset_final = pd.read_csv("dataset_final.csv")

Downloading...
From: https://drive.google.com/uc?id=1y9qBtV71aY6OtEnhfQAxMTWXBBmdv63i
To: /content/dataset_final.csv
100%|██████████| 93.0M/93.0M [00:00<00:00, 264MB/s]


In [ ]:
count = CountVectorizer()
count_matrix = count.fit_transform(dataset_final['deskripsi_keterampilan_final'])
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim)

[[1.         0.15300364 0.15503928 ... 0.09220322 0.14888116 0.16339971]
 [0.15300364 1.         0.09074036 ... 0.05094512 0.07688486 0.14226471]
 [0.15503928 0.09074036 1.         ... 0.1910048  0.12811501 0.28973873]
 ...
 [0.09220322 0.05094512 0.1910048  ... 1.         0.07992076 0.26659877]
 [0.14888116 0.07688486 0.12811501 ... 0.07992076 1.         0.13204784]
 [0.16339971 0.14226471 0.28973873 ... 0.26659877 0.13204784 1.        ]]


In [ ]:
# Simpan model CountVectorizer ke file pickle
with open('count_vectorizer.pkl', 'wb') as f:
    pickle.dump(count, f)

In [ ]:
from google.colab import files
files.download('count_vectorizer.pkl')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# Teks baru yang ingin diuji
new_text = ["job description staff accountant responsible timely accurate preparation financial statement variance report balance sheet reconciliation assigned property assist account group general journal entry bank reconciliation weekly cash reporting special project responsibility include limit prepare monthly financial statement portfolio property produce variance report base analyzed result maintain schedule support balance sheet account include mortgage statement reconciliation capital schedule bank reconciliation submit vp account review prepare post adjust journal entry general ledger review income expense capital purchase accurate coding payment perform bank reconciliation maintain fixed asset track system prepare post bank deposit assist cash management department daily reporting requirement provide additional financial statement general ledger analysis needed participate project business need warrant qualification strong computer skill especially proficient excel ability communicate effectively professionally must possess strong time management analytical interpersonal skill year direct work accounting finance require app folio one site experience plus job type full time k k matching dental insurance disability insurance employee assistance program flexible schedule flexible spending account health insurance life insurance paid time off parental leave professional development assistance tuition reimbursement physical setting office schedule monday friday supplemental pay type bonus pay ability commute relocate norwood reliably commute planning relocate start work require experience gaap year prefer license certification cpa prefer work location one location"]

# Transformasi teks baru menggunakan vectorizer yang sudah fit
new_text_vector = count.transform(new_text)

# Hitung kesamaan kosinus antara teks baru dan semua teks dalam dataset
cosine_sim_new = cosine_similarity(new_text_vector, count_matrix)

# Mengambil 10 dokumen teratas dengan kesamaan tertinggi
top_10_indices = cosine_sim_new[0].argsort()[-10:][::-1]

# Menampilkan 10 dokumen teratas
top_10_titles = dataset_final.iloc[top_10_indices]
top_10_titles

id_pekerjaan  id_perusahaan                skill  \
0        3690843087        6049228  Accounting/Auditing   
865      3674585247       54819446  Accounting/Auditing   
41       3696373506       79378951  Accounting/Auditing   
122      3690876465         104849           Management   
10087    3699082700       35504188  Accounting/Auditing   
5474     3693599611        2762306  Accounting/Auditing   
13494    3701318075           1681  Accounting/Auditing   
6827     3697358549          95985  Accounting/Auditing   
24190    3749357184        1286891  Accounting/Auditing   
4892     3693587409        1286891  Accounting/Auditing   

                                      job title jenis_pekerjaan  \
0                  real estate staff accountant       Full-time   
865                                  accountant       Full-time   
41                             staff accountant       Full-time   
122                            director finance       Full-time   
10087             director corporate accounting       Full-time   
5474                           staff accountant       Full-time   
13494  snr accountant plant accountant rockford       Full-time   
6827                           staff accountant       Full-time   
24190                                accountant        Contract   
4892                    senior staff accountant       Full-time   

        registration_type category sponsor           city          state  \
0      ComplexOnsiteApply    not sponsored        norwood  massachusetts   
865    ComplexOnsiteApply    not sponsored       anniston        alabama   
41     ComplexOnsiteApply    not sponsored   gaithersburg       maryland   
122    ComplexOnsiteApply    not sponsored          omaha       nebraska   
10087  ComplexOnsiteApply        sponsored         irving          texas   
5474   ComplexOnsiteApply    not sponsored  newport beach     california   
13494  ComplexOnsiteApply    not sponsored       rockford       illinois   
6827         OffsiteApply        sponsored   falls church       virginia   
24190        OffsiteApply    not sponsored       san jose     california   
4892         OffsiteApply        sponsored         irving          texas   

              county                       deskripsi_keterampilan_final  
0      united states  job description staff accountant responsible t...  
865    united states  report plant controller accountant responsible...  
41     united states  award win real estate development firm high qu...  
122    united states  ready help shape future travel hospitality cor...  
10087  united states  job title director corporate accounting report...  
5474   united states  lead insurance service company irvine look tal...  
13494  united states  role senior accountant plant accountant salary...  
6827   united states  u premier small business system integrator off...  
24190  united states  accounting bookkeeping proficient knowledge wi...  
4892   united states  location irving tx position overview senior st...